labels:
  ok:  "resp.status == 200"
  err:  "resp.status != 200"
  created: "resp.status == 201"

verify:
  in: true
  out: true

routes:

  /api/v1/users:
    get:
      params: params.json # this defines parameters
      ok: output.json

    post:
      in: Person.json
      created: User.json
